# Single test builder - use with TOOL=TestName
# Example: make -f GNUmakefile.single TOOL=ColorConverter

include $(GNUSTEP_MAKEFILES)/common.make

ifndef TOOL
$(error TOOL variable must be set. Example: make -f GNUmakefile.single TOOL=ColorConverter)
endif

TOOL_NAME = test_$(TOOL)

# Detect LittleCMS
LCMS_INCLUDE := $(shell pkg-config --cflags lcms2 2>/dev/null)
LCMS_LIBS := $(shell pkg-config --libs lcms2 2>/dev/null)
ifeq ($(LCMS_INCLUDE),)
  ifneq ($(wildcard /usr/include/lcms2.h),)
    LCMS_INCLUDE := -I/usr/include
    LCMS_LIBS := -llcms2
  endif
endif

ifneq ($(LCMS_INCLUDE),)
  ifneq ($(LCMS_LIBS),)
    HAVE_LCMS := 1
  endif
endif

# Common includes and libs
COMMON_INCLUDES = -I.. -I../color -I../icc -I../icc/tags -I../visualization -I../SmallStep/SmallStep/Core
COMMON_LIBS = -lgnustep-base

# Test-specific configuration
ifeq ($(TOOL),ColorConverter)
$(TOOL_NAME)_OBJC_FILES = test_ColorConverter.m
$(TOOL_NAME)_INCLUDE_DIRS = -I.. -I../color
$(TOOL_NAME)_TOOL_LIBS = $(COMMON_LIBS)
endif

ifeq ($(TOOL),ICCParser)
$(TOOL_NAME)_OBJC_FILES = test_ICCParser.m
$(TOOL_NAME)_INCLUDE_DIRS = -I.. -I../icc -I../icc/tags $(LCMS_INCLUDE)
$(TOOL_NAME)_TOOL_LIBS = $(COMMON_LIBS) $(LCMS_LIBS)
ifdef HAVE_LCMS
$(TOOL_NAME)_OBJCFLAGS = -DHAVE_LCMS=1
endif
endif

ifeq ($(TOOL),ICCWriter)
$(TOOL_NAME)_OBJC_FILES = test_ICCWriter.m
$(TOOL_NAME)_INCLUDE_DIRS = -I.. -I../icc -I../icc/tags $(LCMS_INCLUDE)
$(TOOL_NAME)_TOOL_LIBS = $(COMMON_LIBS) $(LCMS_LIBS)
ifdef HAVE_LCMS
$(TOOL_NAME)_OBJCFLAGS = -DHAVE_LCMS=1
endif
endif

ifeq ($(TOOL),GamutCalculator)
$(TOOL_NAME)_OBJC_FILES = test_GamutCalculator.m
$(TOOL_NAME)_INCLUDE_DIRS = -I.. -I../color -I../icc $(LCMS_INCLUDE)
$(TOOL_NAME)_TOOL_LIBS = $(COMMON_LIBS) $(LCMS_LIBS)
ifdef HAVE_LCMS
$(TOOL_NAME)_OBJCFLAGS = -DHAVE_LCMS=1
endif
endif

ifeq ($(TOOL),RenderBackend)
$(TOOL_NAME)_OBJC_FILES = test_RenderBackend.m
$(TOOL_NAME)_INCLUDE_DIRS = -I.. -I../visualization -I../SmallStep/SmallStep/Core
$(TOOL_NAME)_TOOL_LIBS = $(COMMON_LIBS) -lgnustep-gui -lSmallStep
endif

ifeq ($(TOOL),CIELABSpaceModel)
$(TOOL_NAME)_OBJC_FILES = test_CIELABSpaceModel.m
$(TOOL_NAME)_INCLUDE_DIRS = -I.. -I../visualization
$(TOOL_NAME)_TOOL_LIBS = $(COMMON_LIBS)
endif

ifeq ($(TOOL),ICCTagEditing)
$(TOOL_NAME)_OBJC_FILES = test_ICCTagEditing.m
$(TOOL_NAME)_INCLUDE_DIRS = -I.. -I../icc -I../icc/tags
$(TOOL_NAME)_TOOL_LIBS = $(COMMON_LIBS)
endif

include $(GNUSTEP_MAKEFILES)/tool.make
