# GNUmakefile for SmallICCer Tests

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = test_ColorConverter

test_ColorConverter_OBJC_FILES = test_ColorConverter.m

test_ColorConverter_INCLUDE_DIRS = \
	-I.. \
	-I../color

test_ColorConverter_TOOL_LIBS = -lgnustep-base

include $(GNUSTEP_MAKEFILES)/tool.make
